### ISSUE TITLE
Using avro-tools to extract schema automatically

### ISSUE THREAD

**Issue by xaduha** [joker1007/embulk-parser-avro#1]
Hi, is this project still worked on? I wonder why it doesn't have dependency on avro-tools.jar to extract the schema automatically from .avro files.

**Comment by joker1007** [comment]
Thanks!
It is reason that Embulk needs `Schema` object for embulk itself (not Avro Schema) before embulk detect input files.
Because of it, schema extraction from file is not simple task.
I want to support this feature too. But I don't have enough time for now.
I wellcome to patch for this.
